name: Node.js CI - TO-DO API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [18]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test
      
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Deploy no Render npm 
        run: |
          curl -X POST "https://api.render.com/v1/services/<SERVICE_ID>/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json"